### ISSUE TITLE
feature: support stream ?

### ISSUE THREAD

**Issue by tst2005** [mpeterv/sha1#1]
Hello,

I create this issue to continue the discuss started [here](https://github.com/kikito/sha1.lua/issues/6)

**Comment by tst2005** [comment]
For the fun and just for the fun
I made a funny ugly hack to create a fake string from file-descriptor
The sha1 require `#str`, `string.byte(str, i, j)` and a concat operation.
See https://github.com/tst2005/lua-fd2string

**Comment by mpeterv** [comment]
Yeah that seems somewhat suboptimal...

**Comment by mpeterv** [comment]
Copying interface draft:

```lua
local state = sha1.new()
state:add(some_input) -- Not necessarily a multiple of block size
state:add(some_input)
...
local hex_sha1 = state.sha1()) -- sha1 of all collected inputs in hex
local bin_sha1 = state.binary() -- sha1 of all collected inputs in binary
state:add(some_input) -- Can keep adding inputs
```

**Comment by mpeterv** [comment]
Python's hashlib uses `update` instead of `add`.

**Comment by tst2005** [comment]
I don't know if you already know [lockbox](https://github.com/somesocks/lua-lockbox).
My current standalone [sha1sum](https://github.com/tst2005/lua-bundles/blob/master/bundles/sha1sum/sha1sum.lua#L509) module built with lockbox


I run your tests and see your optimised sha1 is really faster than my sha1sum/lockbox current solution.

**Comment by mpeterv** [comment]
I've heard of lockbox before, looks like it doesn't really try to optimize for performance, and it doesn't provide a pure Lua version for Lua 5.1 itself either.

**Comment by tst2005** [comment]
http://lua-users.org/lists/lua-l/2018-11/msg00114.html
Thanks for all work you done.
Rest in pease my friend.
